### ISSUE TITLE
Game copy functionality

### ISSUE THREAD

**Issue by tim-coutinho** [spencer-hann/NDimensional_TicTacToe_API#2]
I think I'll need a way to copy a Game object, in order to train a reinforcement agent on it during its training phase.

**Comment by spencer-hann** [comment]
What exactly are you using the copy for? There might be a better way than just copying the whole object (they can get quite large with all the meta-data).
If you really need the whole thing I can write a copy function but it might be better to just use `game.board.copy()`, to just copy the np array, or `game._lines.copy()`, to just copy the dict with the scores, depending on what you need.

**Comment by tim-coutinho** [comment]
I was thinking of training the agent by playing a game with it and another agent as the players, and updating its q-matrix along the way.  So really just doing what tictactoe.py is doing but inside the training section of the agent, so I think I'd need an actual Game object.

**Comment by spencer-hann** [comment]
I'm a little confused. Where in that process do you need a full deep copy? Is it that you need to be able to change the underlying data in the game? you can change the source code for `Game` where the data members are `readonly` to `public`, and make changes yourself, but definitely be careful.

**Comment by tim-coutinho** [comment]
You're right, I suppose I only need access to the size and dim of the game in order to make a copy of it, since it's a clean Game object anyway.

**Comment by spencer-hann** [comment]
are you running multiple games in parallel?

**Comment by tim-coutinho** [comment]
Not for now, probably an option in the future. Right now it looks like at the very start of next_move, it will check if it has been trained yet, and if not, perform the training using the game passed in. I could thread it with multiple games to get more training in, but multithreading with Python is always a little iffy.

**Comment by spencer-hann** [comment]
Don't forget there's a `new_game` function to clear a game object, rather than building a new one from scratch.
